// web/src/lib/JackpotAmount.svelte
<script lang="ts">
	let jackpotAmount = 5789436345;
	$: jackpotAmountReadable = jackpotAmount / 10 ** 8;
</script>

<p>Current jackpot</p>
<h1>
	{jackpotAmountReadable.toLocaleString()} APTOS
</h1>
<p>
	≈ {(366.76).toLocaleString()} USD
</p>

<style>
	* {
		text-align: center;
		margin: 0;
	}
</style>

// web/src/lib/JackpotAmount/JackpotAmount.tsx
import './JackpotAmount.css';

function JackpotAmount() {
  return (
    <>
      <p className="foretitle">Jackpot</p>
      <h1>
        <span className="number">{/*toLocaleString(jackpotAmountReadable)*/}</span>
        APTOS
      </h1>
      <p>≈ {/*jackpotAmountUsd.toLocaleString()*/} USD</p>
    </>
  );
}

export default JackpotAmount;
